services:
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: runner
            MONGO_INITDB_ROOT_PASSWORD: mongodb
