name: my-web-ci-cd

on: [push, pull_request]

env:
    ORIGIN: http://0.0.0.0:8080
    NEXT_PUBLIC_ORIGIN: http://0.0.0.0:8080
    NEXT_PUBLIC_NODE_ENV: test
    MONGO_DB: test-my-web
    MONGO_COLLECTION_CONTACT_FORM_MESSAEG: contact-form-message
    MONGO_ADDRESS: localhost
    MONGO_PORT: 27017
    MONGO_USER: runner
    MONGO_PASSWORD: mongodb

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [18]
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install MongoDB
              uses: supercharge/mongodb-github-action@1.8.0

            - name: Install Depedencies
              run: make install

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              # running test will also execute `build`
              run: make test

            - name: Run Code Generation
              run: make generate
