name: my-web-ci-cd

on: [push, pull_request]

env:
    ORIGIN: http://0.0.0.0:8080
    NEXT_PUBLIC_ORIGIN: http://0.0.0.0:8080
    NEXT_PUBLIC_NODE_ENV: test
    MONGO_DB: test-my-web
    MONGO_COLLECTION_CONTACT_FORM_MESSAEG: contact-form-message
    MONGO_ADDRESS: localhost
    MONGO_PORT: 27017
    MONGO_USER: runner
    MONGO_PASSWORD: mongodb

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install PNPM
              run: |
                  sudo apt install npm
                  npm i --location=global pnpm@8

            - name: Install Mongosh
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget gnupg
                  wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
                  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
                  sudo apt-get update
                  sudo apt-get install -y mongodb-mongosh
            - name: Start Mongo
              run: |
                  sudo service mongod stop 
                  sudo rm /var/lib/mongodb/mongod.lock 
                  sudo mongod --repair --dbpath /var/lib/mongodb 
                  sudo mongod --fork --logpath /var/lib/mongodb/mongodb.log --dbpath /var/lib/mongodb 
                  sudo service mongod start

            - name: Ping Mongosh
              run: make echo-mongo

            - name: Install Depedencies
              run: make install

            - name: MongoDB Migration
              run: make migrate-mongo

            - name: Run Code Generation
              run: make generate

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              run: make test

            - name: Run Build
              run: make build
